#include <exception>

class OutOfBoundsException : std::exception
{
};